# Generated by Django 3.2.1 on 2021-06-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.CharField(max_length=30)),
                ('floor_plan', models.ImageField(upload_to='uploads/')),
                ('video', models.FileField(default='', upload_to='uploads/')),
                ('image_1', models.ImageField(upload_to='uploads/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('bathroom', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('kitchen', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('status', models.CharField(choices=[('re', 'Rent'), ('sa', 'Sale')], max_length=10)),
                ('date_built', models.DateField()),
                ('balcony', models.IntegerField()),
                ('archive', models.BooleanField(default=False)),
                ('parking', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=30)),
                ('land_area', models.IntegerField()),
                ('property_lot_size', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
